

POWERLEVEL10K_APPLE_ICON='\uE26E'
POWERLEVEL10K_LINUX_ICON='\uE271'
POWERLEVEL10K_RUBY_ICON='\uE847 '
POWERLEVEL10K_PYTHON_ICON='\U1F40D '

POWERLEVEL10K_BACKGROUND_JOBS_ICON='\uE82F '
DISABLE_AUTO_TITLE="true"

POWERLEVEL10K_VCS_GIT_ICON=''
POWERLEVEL10K_VCS_TAG_ICON='\uE817 '
POWERLEVEL10K_VCS_STAGED_ICON='\u00b1'
POWERLEVEL10K_VCS_STASH_ICON='\uE133 '
POWERLEVEL10K_VCS_UNTRACKED_ICON='\u25CF'
POWERLEVEL10K_VCS_UNSTAGED_ICON='\u00b1'
POWERLEVEL10K_VCS_INCOMING_CHANGES_ICON='\u2193'
POWERLEVEL10K_VCS_OUTGOING_CHANGES_ICON='\u2191'
#
POWERLEVEL10K_VCS_MODIFIED_BACKGROUND='yellow'
POWERLEVEL10K_VCS_UNTRACKED_BACKGROUND='yellow'
#POWERLEVEL10K_VCS_UNTRACKED_ICON='?'
#
#POWERLEVEL10K_PROMPT_ON_NEWLINE=true
#POWERLEVEL10K_RPROMPT_ON_NEWLINE=false
#POWERLEVEL10K_MULTILINE_FIRST_PROMPT_PREFIX="╭"
#POWERLEVEL10K_MULTILINE_LAST_PROMPT_PREFIX="╰\u2570\uf460 "

POWERLEVEL10K_LEFT_PROMPT_ELEMENTS=(os_icon context dir vcs)
POWERLEVEL10K_RIGHT_PROMPT_ELEMENTS=(background_jobs virtualenv rbenv rvm time status)

#POWERLEVEL10K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL10K_SHORTEN_DIR_LENGTH=3
POWERLEVEL10K_SHORTEN_STRATEGY=truncate_folders
#
POWERLEVEL10K_TIME_FORMAT="%D{%H:%M \uE868  %d.%m.%y}"
#
# #POWERLEVEL10K_VCS_MODIFIED_BACKGROUND='orange'
POWERLEVEL10K_STATUS_VERBOSE=false
export DEFAULT_USER="$USER"